name: 'Generate Blog'
description: 'Generate my hugo blog.'
runs:
  using: "composite"
  steps:          
    - name: Fix File Modify Time
      shell: bash
      run: git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "latest"
        extended: true
      
    - name: Build
      shell: bash
      run: hugo --minify --gc
      