name: 'Generate Blog'
description: 'Generate my hugo blog.'
runs:
  using: "composite"
  steps:
    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.5' # The Go version to download (if necessary) and use.
        cache: true
          
    - name: Fix File Modify Time
      shell: bash
      run: git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "latest"
        extended: true
      
    - name: Build
      shell: bash
      run: hugo --minify --gc
      